/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 2515a25fa56853f05c2118b504cb35f3)
interface __BaseEnv_Env {
	AI: Ai;
	VOICE_AGENT_TOKEN: string;
	VoiceAgent: DurableObjectNamespace<import("./src/index").VoiceAgent>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "VoiceAgent";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "VOICE_AGENT_TOKEN">> {}
}
