import { useEffect, useState } from "react";
import "./App.css";

interface Surface {
	id: string;
	label: string;
	path: string;
	kind: "text" | "json";
}

interface SiteInfo {
	site: { name: string; description: string; origin: string };
	webBotAuthEnabled: boolean;
	surfaces: Surface[];
}

interface Resource {
	slug: string;
	title: string;
	summary: string;
	topics: string[];
	category: string | null;
}

function useSiteInfo() {
	const [info, setInfo] = useState<SiteInfo | null>(null);
	useEffect(() => {
		fetch("/api/site")
			.then((r) => r.json())
			.then(setInfo)
			.catch(() => setInfo(null));
	}, []);
	return info;
}

function SurfacePreview({ surface }: { surface: Surface }) {
	const [open, setOpen] = useState(false);
	const [body, setBody] = useState<string>("");
	const [loading, setLoading] = useState(false);
	const [copied, setCopied] = useState(false);

	async function load() {
		setLoading(true);
		try {
			const res = await fetch(surface.path);
			const text = await res.text();
			setBody(
				surface.kind === "json"
					? JSON.stringify(JSON.parse(text), null, 2)
					: text,
			);
		} catch {
			setBody("Failed to load surface.");
		} finally {
			setLoading(false);
		}
	}

	function toggle() {
		const next = !open;
		setOpen(next);
		if (next && !body) load();
	}

	async function copy() {
		await navigator.clipboard.writeText(body);
		setCopied(true);
		setTimeout(() => setCopied(false), 1500);
	}

	return (
		<div className="surface">
			<div className="surface-head">
				<div>
					<span className="surface-label">{surface.label}</span>
					<code className="surface-path">{surface.path}</code>
				</div>
				<div className="surface-actions">
					<a href={surface.path} target="_blank" rel="noreferrer">
						Open ↗
					</a>
					<button onClick={toggle}>{open ? "Hide" : "Preview"}</button>
				</div>
			</div>
			{open && (
				<div className="surface-body">
					{loading ? (
						<p className="muted">Loading…</p>
					) : (
						<>
							<button className="copy" onClick={copy}>
								{copied ? "Copied" : "Copy"}
							</button>
							<pre>{body}</pre>
						</>
					)}
				</div>
			)}
		</div>
	);
}

export default function App() {
	const info = useSiteInfo();
	const [resources, setResources] = useState<Resource[]>([]);

	useEffect(() => {
		fetch("/api/resources")
			.then((r) => r.json())
			.then((d) => setResources(d.resources ?? []))
			.catch(() => setResources([]));
	}, []);

	if (!info) {
		return (
			<main className="container">
				<p className="muted">Loading…</p>
			</main>
		);
	}

	return (
		<main className="container">
			<header>
				<p className="kicker">AI Agent Visibility</p>
				<h1>{info.site.name}</h1>
				<p className="lede">{info.site.description}</p>
				<p className="muted">
					One enriched content store, served to AI agents through every
					discovery surface below — generated by Workers AI, cached in KV.
				</p>
			</header>

			<section>
				<h2>Agent surfaces</h2>
				<p className="muted">
					The same content, in whichever convention an agent prefers.
				</p>
				<div className="surfaces">
					{info.surfaces.map((s) => (
						<SurfacePreview key={s.id} surface={s} />
					))}
				</div>
				{info.webBotAuthEnabled && (
					<p className="muted">
						Web Bot Auth identity surface is <strong>enabled</strong> at{" "}
						<code>/.well-known/web-bot-auth/directory</code>.
					</p>
				)}
			</section>

			<section>
				<h2>Indexed pages ({resources.length})</h2>
				<div className="cards">
					{resources.map((r) => (
						<article className="card" key={r.slug}>
							<h3>
								<a href={`/${r.slug}.md`} target="_blank" rel="noreferrer">
									{r.title}
								</a>
							</h3>
							{r.category && <span className="tag">{r.category}</span>}
							<p>{r.summary}</p>
							{r.topics.length > 0 && (
								<p className="topics">{r.topics.join(" · ")}</p>
							)}
						</article>
					))}
				</div>
			</section>

			<footer>
				<p className="muted">
					Built on Cloudflare Workers + Workers AI + KV. Replace the sample
					content in <code>src/lib/content.ts</code> or POST your own pages to{" "}
					<code>/api/resources</code>.
				</p>
			</footer>
		</main>
	);
}
