# Top-level configuration
name = "stripe-stream-example"
compatibility_date = "2022-10-31"

[vars]
PRICE = ""
STRIPE_PUBLISHABLE_KEY = ""
STRIPE_SECRET_KEY = ""
HOST = "http://localhost:8788"
CLOUDFLARE_ACCOUNT_ID = ""
CLOUDFLARE_API_TOKEN = ""
CLOUDFLARE_STREAM_VIDEO_UID = "3a1c3d8e98e5262734bf1d8c82090ac9"
CLOUDFLARE_STREAM_SUBDOMAIN = "customer-m033z5x00ks6nunl"