name: "\U0001F680 Template Request"
description: Have a suggestion for a new template? Let us know!
title: "\U0001F680 Template Request:"
labels: ["enhancement"]

body:
  - type: markdown
    attributes:
      value: |
        ## Template Request Form
        Thank you for taking the time to file a feature request! Please let us know what template you'd like to see in the library.

  - type: textarea
    attributes:
      label: Describe the stack
      description: A clear description of what you want in the new template.
    validations:
      required: true
