/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: aac2371e967f8049b2d3dd285c2d5d9b)
interface __BaseEnv_Env {
	ASSETS: Fetcher;
	ROUTE_ADDRESS: "support@company.example";
	FORWARD_TO: "owner@mailbox.example";
	ALLOWED_SENDERS: "trusted@partner.example";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
