// Generated by wrangler
/// <reference types="@cloudflare/workers-types" />

interface Env {
	AIDD_SPEC?: string;
	AIDD_NAME?: string;
	AIDD_DESCRIPTION?: string;
	AIDD_WEBSITE?: string;
	AIDD_CONTACT?: string;
	AIDD_LOGO?: string;
	AIDD_ENTITY_TYPE?: string;
	AIDD_JSONLD?: string;
	AIDD?: KVNamespace;
}

