#!/usr/bin/env node

/**
 * Provision the Cloudflare resources required by the Internal Sites Platform.
 *
 * This script is intentionally separate from `npm run build`. It runs only when
 * a developer explicitly requests setup or immediately before deployment.
 */

const { execFileSync } = require("child_process");
const fs = require("fs");
const path = require("path");

const PROJECT_ROOT = path.join(__dirname, "..");

const red = "\x1b[31m";
const green = "\x1b[32m";
const yellow = "\x1b[33m";
const blue = "\x1b[34m";
const cyan = "\x1b[36m";
const reset = "\x1b[0m";

function log(color, message) {
	console.log(`${color}${message}${reset}`);
}

function readWranglerVar(varName) {
	const configPath = path.join(PROJECT_ROOT, "wrangler.jsonc");
	if (!fs.existsSync(configPath)) return null;

	const content = fs.readFileSync(configPath, "utf-8");
	const match = content.match(new RegExp(`"${varName}"\\s*:\\s*"([^"]+)"`));
	return match?.[1] || null;
}

function getDispatchNamespaceFromConfig() {
	const configPath = path.join(PROJECT_ROOT, "wrangler.jsonc");
	if (!fs.existsSync(configPath)) return "internal-sites";

	const content = fs.readFileSync(configPath, "utf-8");
	const match = content.match(/"namespace"\s*:\s*"([^"]+)"/);
	return match?.[1] || "internal-sites";
}

function getAccountId(env = process.env) {
	return (
		env.CLOUDFLARE_ACCOUNT_ID ||
		env.ACCOUNT_ID ||
		env.CF_ACCOUNT_ID ||
		readWranglerVar("ACCOUNT_ID") ||
		null
	);
}

function runWrangler(args, env = process.env) {
	const wranglerCli = require.resolve("wrangler/bin/wrangler.js", {
		paths: [PROJECT_ROOT],
	});

	return execFileSync(process.execPath, [wranglerCli, ...args], {
		cwd: PROJECT_ROOT,
		encoding: "utf-8",
		env,
		stdio: "pipe",
	});
}

function commandOutput(error) {
	return [error.stdout, error.stderr]
		.filter(Boolean)
		.map((output) => output.toString())
		.join("\n");
}

function ensureDispatchNamespace(namespaceName, executeWrangler = runWrangler) {
	log(blue, `Creating dispatch namespace '${namespaceName}'...`);

	try {
		executeWrangler(["dispatch-namespace", "create", namespaceName]);
		log(green, `  Dispatch namespace '${namespaceName}' created.`);
	} catch (error) {
		const output = commandOutput(error);
		if (
			output.includes("already exist") ||
			output.includes("A namespace with this name")
		) {
			log(green, `  Dispatch namespace '${namespaceName}' already exists.`);
			return;
		}

		if (output.trim()) {
			console.error(output.trim());
		}

		throw new Error(
			`Could not create dispatch namespace '${namespaceName}'. Verify that Workers for Platforms is enabled and that your Cloudflare credentials have Workers Scripts Edit permission.`,
			{ cause: error },
		);
	}
}

function updateWranglerConfig(accountId) {
	const configPath = path.join(PROJECT_ROOT, "wrangler.jsonc");
	if (!fs.existsSync(configPath)) {
		throw new Error("wrangler.jsonc was not found.");
	}

	const content = fs.readFileSync(configPath, "utf-8");
	const updated = content.replace(
		/"ACCOUNT_ID"\s*:\s*"[^"]*"/,
		`"ACCOUNT_ID": "${accountId}"`,
	);

	if (
		updated === content &&
		!content.includes(`"ACCOUNT_ID": "${accountId}"`)
	) {
		throw new Error("Could not find ACCOUNT_ID in wrangler.jsonc vars.");
	}

	if (updated !== content) {
		fs.writeFileSync(configPath, updated, "utf-8");
		log(green, "  Set ACCOUNT_ID in wrangler.jsonc.");
	}
}

function writeDevVars(accountId, dispatchToken) {
	const devVarsPath = path.join(PROJECT_ROOT, ".dev.vars");
	const vars = {};

	if (fs.existsSync(devVarsPath)) {
		for (const line of fs.readFileSync(devVarsPath, "utf-8").split("\n")) {
			const match = line.match(/^([A-Z_]+)="?([^"]*)"?$/);
			if (match) vars[match[1]] = match[2];
		}
	}

	vars.ACCOUNT_ID = accountId;
	if (dispatchToken) vars.DISPATCH_NAMESPACE_API_TOKEN = dispatchToken;

	const lines = ["# Auto-generated by setup script"];
	for (const [key, value] of Object.entries(vars)) {
		lines.push(`${key}="${value}"`);
	}

	fs.writeFileSync(devVarsPath, `${lines.join("\n")}\n`, "utf-8");
	log(green, "  .dev.vars written.");
}

function provision({ env = process.env, executeWrangler = runWrangler } = {}) {
	const accountId = getAccountId(env);
	const namespaceName = getDispatchNamespaceFromConfig();
	const dispatchToken = env.DISPATCH_NAMESPACE_API_TOKEN || null;

	console.log("");
	log(blue, "Internal Sites Platform -- Cloudflare Setup");
	log(blue, "──────────────────────────────────────────");
	console.log("");

	if (!accountId) {
		throw new Error(
			"Cloudflare Account ID is required. Set CLOUDFLARE_ACCOUNT_ID (recommended) or ACCOUNT_ID before running setup.",
		);
	}

	log(cyan, `  Account ID: ${accountId.substring(0, 8)}...`);
	log(cyan, `  Namespace: ${namespaceName}`);
	console.log("");

	// Provision first. A failed setup must stop before `wrangler deploy` runs.
	ensureDispatchNamespace(namespaceName, (args) =>
		executeWrangler(args, {
			...env,
			CLOUDFLARE_ACCOUNT_ID: accountId,
		}),
	);
	updateWranglerConfig(accountId);
	writeDevVars(accountId, dispatchToken);

	console.log("");
	log(green, "  Cloudflare setup complete.");
	console.log("");
}

if (require.main === module) {
	try {
		provision();
	} catch (error) {
		console.log("");
		log(red, `Setup failed: ${error.message}`);
		if (!process.env.WORKERS_CI) {
			log(
				yellow,
				"Run `npm run setup` again after correcting the account, credentials, or Workers for Platforms access.",
			);
		}
		process.exitCode = 1;
	}
}

module.exports = {
	ensureDispatchNamespace,
	provision,
};
