/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: d32716bfdb77e20c8956ab12f24e5930)
interface __BaseEnv_Env {
	EMAIL: SendEmail;
	ASSETS: Fetcher;
	FROM_ADDRESS: "notifications@company.example";
	TO_ADDRESS: "recipient@mailbox.example";
	SEND_EMAIL_AUTH_TOKEN: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
