/**
 * Shared types for the Commerce llms.txt prototype.
 */

/** Raw product data — what a merchant's database actually stores. */
export interface RawProduct {
	slug: string;
	name: string;
	price: number;
	currency: string;
	category: string;
	inStock: boolean;
	stockCount: number;
	/** Raw manufacturer specs — the "20,000 BTU" style data. */
	specs: Record<string, string>;
	/** Basic description from the merchant's CMS. */
	description: string;
	/** Image URL */
	imageUrl?: string;
	/** Last time inventory was updated */
	lastUpdated: string;
}

/** Enriched product — after Workers AI transforms specs into agent-friendly language. */
export interface EnrichedProduct extends RawProduct {
	/** Agent-friendly summary generated by Workers AI. */
	agentSummary: string;
	/** Use-case tags extracted by the LLM (e.g., "car camping", "backpacking", "family trips"). */
	useCaseTags: string[];
	/** Key selling points in plain language. */
	highlights: string[];
	/** Who this product is best for. */
	bestFor: string;
}
