name: (CD) workers.new

on:
  push:
    branches:
      - 'main'
    paths:
      - 'packages/workers.new/**'

jobs:
  deploy:
    name: Node.js v16
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/create-cloudflare

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install
        run: npm install

      - name: TypeCheck
        run: npm run types

      - name: Compiles
        run: npm run build
