name: "Update Dependencies"

on:
  schedule:
    - cron: "0 15 * * 1"

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup

      - name: "Process and update dependencies"
        run: "pnpm -w update:deps"
